### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by MrGallo** [DMansoori/pbd-solutions-#2]
https://github.com/DMansoori/pbd-solutions-/blob/8a81f025b6739b6a9f93dd4f2be36e30cadfcb43/FirstProg.java#L3-L7

Try to limit the amount of whitespace in the code.

Should be:
```java
 		System.out.println("Hello World"); 
 	} 
 } 
```

**Comment by DMansoori** [comment]
Thanks sir!
